---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ./

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Lint markdown files
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "./"

  jsonlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Run JSON Lint
        env:
          SHOW_ERRORS: true
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
