name: release-main

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF_NAME#v} >> $GITHUB_OUTPUT

      - name: Build and publish
        run: |
          uv version $RELEASE_VERSION --frozen
          make build-and-publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
